# Generated by Django 4.2.7 on 2023-11-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('vendor_app', '0003_alter_purchaseorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
